package com.honsoft.web.mapper.mysql;

import com.honsoft.web.entity.Users;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Fri May 14 08:38:47 KST 2021
	 */
	@Insert({ "insert into users (id, name, ", "email)", "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
			"#{email,jdbcType=VARCHAR})" })
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Fri May 14 08:38:47 KST 2021
	 */
	@Select({ "select", "id, name, email", "from users" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "email", property = "email", jdbcType = JdbcType.VARCHAR) })
	List<Users> selectAll();
}